method: random
metric:
  goal: minimize
  name: train_loss
early_terminate:
  type: hyperband
  min_iter: 30
  eta: 3
  max_iter: 80
parameters:
  batch_size:
    values: [32, 64]
  ff_size:
    values: [8, 16, 32, 64, 128, 256]
  dropout:
    distribution: "uniform"
    min: 0.1
    max: 0.3
  learning_rate:
    distribution: "uniform"
    min: 0
    max: 0.001
  num_heads:
    values: [1, 2, 4]
  num_layers:
    distribution: "int_uniform"
    min: 1
    max: 8
  experiment:
    value: "drone_example"
  pickle_path:
    value: "src/dataset/data/0814/drone_example/processed.pkl"
  weights_path:
    value: "src/dataset/data/0814/drone_example/weights.pkl"
command:
  - ${env}
  - python3
  - src/train.py
  - "-hp"
  - "src/configs/tf_md.yaml"
project: "faab_autoencoder_minidataset"
description: ""
entity: "faab-hyperparams"
